import "jsr:@supabase/functions-js/edge-runtime.d.ts";

function fallbackArtifacts(plan: any) {
  const readme = `# Generated App

This app was generated by MergeForge.

## Summary

${plan.summary || "Merged app scaffold"}

## Pages

${(plan.pages || []).map((p: any) => `- ${p.path}: ${p.title}`).join("\n")}

## Routes

${(plan.routes || []).map((r: any) => `- ${r.method} ${r.path}`).join("\n")}
`;

  const envExample = (plan.env_vars || [])
    .map((name: string) => `${name}=`)
    .join("\n");

  const packageJson = JSON.stringify(
    {
      name: "generated-mergeforge-app",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start"
      },
      dependencies: {
        next: "15.3.3",
        react: "19.1.0",
        "react-dom": "19.1.0",
        "@supabase/supabase-js": "^2.56.0"
      }
    },
    null,
    2
  );

  return [
    {
      path: "README.md",
      content: readme,
      artifact_type: "readme"
    },
    {
      path: ".env.example",
      content: envExample,
      artifact_type: "env"
    },
    {
      path: "package.json",
      content: packageJson,
      artifact_type: "code"
    },
    {
      path: "app/page.tsx",
      content: `export default function HomePage() {
  return (
    <main style={{ padding: 24 }}>
      <h1>Generated MergeForge App</h1>
      <p>${plan.summary || "Your generated app is ready to expand."}</p>
    </main>
  );
}
`,
      artifact_type: "code"
    }
  ];
}

Deno.serve(async (req) => {
  try {
    const { plan } = await req.json();

    return new Response(
      JSON.stringify({
        artifacts: fallbackArtifacts(plan || {})
      }),
      {
        headers: { "Content-Type": "application/json" }
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : "Unknown error"
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" }
      }
    );
  }
});
